### ISSUE TITLE
Completed Task buttons

### ISSUE THREAD

**Issue by mschae16** [anajauregui/2DoBox-Pivot#6]
Add a button to each card called "Completed Task" Add a "Show completed ToDos" and work on page load functionality (filtering).

**Comment by ana-jauregui** [comment]
I have been able to finally complete up to the last bullet point on Phase 3- marking TODO's as completed... 
*When the user clicks the show completed TODOs, the completed TODOs should be loaded back onto the top of the TODO list. (Currently working on this piece)
